nosetests miscellaneous/python-tutorials
nosetests miscellaneous/regex
nosetests contests/w6
nosetests contests/projecteuler
nosetests algoritms/warmup
nosetests algoritms/search
nosetests algoritms/math
nosetests algoritms/arrays-and-sorting
nosetests algoritms/combinatorics
nosetests algoritms/dynamic-programming
nosetests algoritms/graph
